name: Update README

on: [push]
  #push:
  #schedule:
 #   - cron: "0 */1 * * *"

jobs:
  concat-md-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - shell: bash
        run: cat README-base.md subsec1/README.md subsec2/README.md > README.md

      - uses: stefanzweifel/git-auto-commit-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: master
    
